# Change baseurl before deploy
baseurl =  "https://chiacole91.github.io/website/"#"https://crispy-waddle-4wvr9jj9w6r39xr-1313.app.github.dev/"#

languageCode = "en-us"
title = "Chiara Colesanti Senni"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

[pagination]
pagerSize = 5